### ISSUE TITLE
Add documentation on running the project

### ISSUE THREAD

**Issue by moan0s** [elliotwoods/SilentStream#12]
I know this project is probably no longer used/maintained but it's exactly what I was searching for. I would love to have some documentation on running this and could maybe see myself to develop it!

**Comment by moan0s** [comment]
So this seems to be a express.js app and can be run by 
- First installing dependencies with `npm install`
- and running the app with `node app.js`

Then I was able to visit localhost:9000 but found no paths of the app `/listen` or `/listen.html` did not work - any help appreciated

I never worked with express.js so I probably ask very obvious questions

**Comment by elliotwoods** [comment]
Dear @moan0s 
I spent a few hours to get this tuned and working but was in a bit of a rush for a specific project so didn't document well. If you are able to improve on this code and get it documented / have a better run routine it would be fantastic. Also if you want to just rip parts and make your own layout/repo (crediting this one) that's also welcome.

I just tried running it now by opening the folder in Visual Studio Code and opening app.js and pressing run, then i can visit `http://localhost:5000/` to get the receiving page and `http://localhost:5000/broadcast.html` to get the sending page (not very secure!)

if i hit play on the listening page then i get audio feedback
![image](https://github.com/elliotwoods/SilentStream/assets/328294/5a78e3da-8426-4a0b-ad2a-e5eed3ae7bb1)

i.e. it is working fine, but yes needs some documentation

**Comment by elliotwoods** [comment]
I've changed the startup and added notes to readme.md
It's still very sparse but should get you started up

**Comment by moan0s** [comment]
Thank you so much, I got it running! Now to experiment a bit with getting music in there ...

**Comment by elliotwoods** [comment]
good luck!
any pull requests (e.g. for readme) would be very welcome
